# Generated by Django 5.1.3 on 2024-11-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_alter_answer_question_alter_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('OPEN', 'Open-ended')], default='MCQ', max_length=10),
        ),
    ]
