# Generated by Django 5.1.3 on 2024-11-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
    ]
