# Generated by Django 5.1.3 on 2024-11-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0012_remove_answer_score_question_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='guest',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
