# Generated by Django 5.1.3 on 2024-11-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0013_answer_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='guest',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
