# Generated by Django 5.1.3 on 2024-11-22 16:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0015_answer_explanation_alter_answer_guest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 20, 1, 19, 483333)),
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 20, 1, 19, 483333)),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 20, 1, 19, 483333)),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 20, 1, 19, 483333)),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 20, 1, 19, 483333)),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 20, 1, 19, 483333)),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 11, 22, 20, 1, 19, 483333))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 11, 22, 20, 1, 19, 483333))),
                ('answer', models.TextField(verbose_name='Answer')),
                ('correct', models.BooleanField(default=False, verbose_name='Correct')),
                ('guest', models.CharField(blank=True, max_length=25, null=True)),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Explanation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='your_answers', to='quiz_app.question', verbose_name='Question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
