# Generated by Django 5.1.3 on 2024-11-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0017_alter_answer_created_at_alter_answer_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation'),
        ),
        migrations.AddField(
            model_name='answer',
            name='guest',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Guest'),
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
