# Generated by Django 5.1.3 on 2024-11-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0022_quizscore_created_at_quizscore_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='guest',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
