# Generated by Django 5.1.3 on 2024-11-20 20:09

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_date_joined_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAnonymousUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
            ],
            bases=(django.contrib.auth.models.AnonymousUser, models.Model),
        ),
    ]
