# Generated by Django 5.1.3 on 2024-11-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customanonymoususer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomAnonymousUser',
        ),
    ]
